replace_existing_fact(sensorValue(brightness_outside ,0), sensorValue(brightness_outside, 42))
replace_existing_fact(sensorValue(temperature ,10), sensorValue(temperature, 33))
replace_existing_fact(sensorValue(temperature_outside ,8), sensorValue(temperature_outside, 26))
replace_existing_fact(sensorValue(outside_noise ,20), sensorValue(outside_noise, 15))
set(nullPreference)
replace_existing_fact(sensorValue(brightness ,0), sensorValue(brightness, 0))
replace_existing_fact(sensorValue(temperature ,33), sensorValue(temperature, 33))
set(turn_on)
replace_existing_fact(sensorValue(brightness ,0), sensorValue(brightness, 100))
replace_existing_fact(sensorValue(temperature ,33), sensorValue(temperature, 100))
replace_existing_fact(actuatorValue(cornerLight ,100), actuatorValue(cornerLight, 10))
replace_existing_fact(sensorValue(brightness ,100), sensorValue(brightness, 100))
replace_existing_fact(sensorValue(temperature ,100), sensorValue(temperature, 100))
set(turn_off)
replace_existing_fact(sensorValue(brightness ,100), sensorValue(brightness, 0))
replace_existing_fact(sensorValue(temperature ,100), sensorValue(temperature, 33))
replace_existing_fact(actuatorValue(cornerLight ,0), actuatorValue(cornerLight, 10))
replace_existing_fact(sensorValue(brightness ,0), sensorValue(brightness, 10))
replace_existing_fact(sensorValue(temperature ,33), sensorValue(temperature, 33))
replace_existing_fact(actuatorValue(cornerLight ,10), actuatorValue(cornerLight, 100))
replace_existing_fact(sensorValue(brightness ,10), sensorValue(brightness, 100))
replace_existing_fact(sensorValue(temperature ,33), sensorValue(temperature, 33))
sensor(inside111, light)
sensorValue(inside111, 0)
inside(inside111)
replace_existing_fact(sensorValue(inside111 ,0), sensorValue(inside111, 100))
replace_existing_fact(sensorValue(brightness ,100), sensorValue(brightness, 100))
replace_existing_fact(sensorValue(inside111 ,100), sensorValue(inside111, 100))
replace_existing_fact(sensorValue(temperature ,33), sensorValue(temperature, 33))
