set(movie)
replace_existing_fact(actuatorValue(mainLight ,_), actuatorValue(mainLight, 47))
replace_existing_fact(sensorValue(brightness_outside ,_), sensorValue(brightness_outside, 60))
replace_existing_fact(sensorValue(temperature ,_), sensorValue(temperature, 19))
replace_existing_fact(sensorValue(temperature_outside ,_), sensorValue(temperature_outside, 29))
replace_existing_fact(sensorValue(outside_noise ,_), sensorValue(outside_noise, 18))
remove_existing_fact(preferencesInstance(movie,  _, _, _))
set(nullPreference)
set(nullPreference)
set(sleep)
set(turn_off)
set(study)
set(study)
set(study)
