replace_existing_fact(sensorValue(brightness_outside ,_), sensorValue(brightness_outside, 44.5))
replace_existing_fact(sensorValue(temperature ,_), sensorValue(temperature, 27))
replace_existing_fact(sensorValue(temperature_outside ,_), sensorValue(temperature_outside, 26))
replace_existing_fact(sensorValue(outside_noise ,_), sensorValue(outside_noise, 21))
replace_existing_fact(sensorValue(brightness_outside ,_), sensorValue(brightness_outside, 58.5))
replace_existing_fact(sensorValue(temperature ,_), sensorValue(temperature, 23))
replace_existing_fact(sensorValue(temperature_outside ,_), sensorValue(temperature_outside, 26))
replace_existing_fact(sensorValue(outside_noise ,_), sensorValue(outside_noise, 19))preferencesInstance(tanoIsTheBest, light, [roller_shutter], 0)
preferencesInstance(TanoIsTheBest, light, [roller_shutter], 0)
preferencesInstance(TanoIsTheBest, light, roller_shutter, 0)
sensor(mauro, light)
